"""empty message

Revision ID: 40d84736e041
Revises: ed99c2c7d562
Create Date: 2022-08-13 16:46:37.976037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d84736e041'
down_revision = 'ed99c2c7d562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('website_link', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('looking_for_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'looking_for_venue')
    op.drop_column('Artist', 'website_link')
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###
